### ISSUE TITLE
gb2av belegt 10 DB-Connections

### ISSUE THREAD

**Issue by schmandr** [sogis/gb2av-web-service#3]
Ich musste heute die PostgreSQL-DB restarten, und nach dem Restart nahm sich gb2av direkt 10 DB-Verbindungen. Das ist zwar noch nicht ganz tragisch, aber doch etwas erstaunlich. Wenn sich mit wenig Aufwand etwas dagegen machen liesse, wäre das zu begrüssen. Chancen dafür müssten wohl bestehen, denn vom avdpool-Service, der ähnlich funktioniert, sah ich gar keine DB-Verbindung.

**Comment by edigonzales** [comment]
Immerhin nachvollziehbar: https://github.com/sogis/gb2av-web-service/blob/master/src/main/resources/application.properties#L37

**Comment by edigonzales** [comment]
ja und nein wegen avdpool: Diese Konfiguration braucht es nur weil wir hier ein JDBC-Idempotent-Repository verwenden und wir beim avdpool "ups und weg ist das File"-Ansatz verfolgen :)

**Comment by edigonzales** [comment]
fixed: https://github.com/sogis/gb2av-web-service/commit/bca3bc2c5dc45ef9d81cb5bdb833513925bdce49

Ich bin mir aber nicht sicher, ob das jetzt ok ist (alles auf zwei). Kannst du das kurz beobachten?

**Comment by schmandr** [comment]
Es hat leider nichts genützt: 
![db-connections1](https://user-images.githubusercontent.com/3601534/82226506-de8fe280-9926-11ea-8dc4-3eb8aff0d2a9.png)
![db-connections2](https://user-images.githubusercontent.com/3601534/82226512-e059a600-9926-11ea-83e0-70cc0f4b19fe.png)

Meistens sieht man der oberen Zustand, und ca. minütlich den unteren. Manchmal ist auch z.B. nur ein Eintrag mit `COMMIT` da, plus 9 mit `SET application_name = 'gb2av'`. Oder einzig und allein 10 Eintrage mit `SET application_name = 'gb2av'`. Es scheint also, wie wenn sie immer auf 10 "aufgefüllt" würden.

**Comment by schmandr** [comment]
Weil das nun ja doch etwas überraschend ist, habe ich noch das JAR aus dem Pod extrahiert und reingeschaut. Es steht schon so drin, wie es soll:
```
spring.datasource.tomcat.max-wait=20000
spring.datasource.tomcat.max-active=2
spring.datasource.tomcat.max-idle=2
spring.datasource.tomcat.min-idle=2 
```

**Comment by schmandr** [comment]
Nach dem Start des Pods sind übrigens gleich 10 Verbindungen da. Es gäbe offenbar auch `setInitialSize`, was noch einen Versuch wert wäre.

**Comment by edigonzales** [comment]
Ich Idiot: `.tomcat.` bedeutet, dass man die Connection Pool Implementierung von Tomcat verwendet. Defaultmässig wird aber Hikari verwendet, d.h.:

`spring.datasource.hikari.maximumPoolSize=2`

Bitte nochmals kurz prüfen.

**Comment by schmandr** [comment]
Sehr gut, jetzt funktioniert's. Belegt nur noch 2 Connections.

Dann ist es jetzt an mir, dies noch in Int. und Prod. auszurollen.
